### ISSUE TITLE
Mention the fact that all HTML/Form helper functions return HtmlString objects? 

### ISSUE THREAD

**Issue by ZhangYiJiang** [LaravelCollective/docs#30]
This isn't documented anywhere, but the fact that all Form and HTML helper functions return `HtmlString` objects means that they can be safely used with normal escaped Blade template tags. ie. 

``` php
{{ Form::open() }}
```

works just as fine as 

``` php
{!! Form::open() !!}
```

This is probably a safety feature, and there is a minor performance penalty for the former, but it might be worth mentioning anyway?

**Comment by redgluten** [comment]
Any inputs on the safety and performance concerns @tshafer @adamgoose ?
