### ISSUE TITLE
Html documentation for versions 5.5 and 5.6

### ISSUE THREAD

**Issue by ghost** [LaravelCollective/docs#45]
Currently there are no specific docs for versions 5.5 and 5.6 of the html package. They only go up to 5.4.

I'm not completely aware of all the changes between those (if any), but details like package auto-discovery from Laravel 5.5 and so could be better documented.

Is this something desirable? I'd be glad to work on it.

**Comment by tshafer** [comment]
That would be wonderful.

**Comment by ghost** [comment]
Great! I'll give it a try. Can you please create branches for 5.5 and 5.6?

**Comment by ghost** [comment]
I already have a couple of branches with the changes. I need the new branches here so I can create a PR :)

**Comment by tshafer** [comment]
I have created the branches.

**Comment by insign** [comment]
I made a PR for Remote doc
