### ISSUE TITLE
Page not found.

### ISSUE THREAD

**Issue by datomnurdin** [LaravelCollective/docs#56]
All the doc pages not found. Any solution to this?

**Comment by jwheat** [comment]
Everything seems ok here.  What happens when you visit this url - https://github.com/LaravelCollective/docs

**Comment by cotiga** [comment]
https://github.com/LaravelCollective/docs
OK
https://github.com/LaravelCollective/docs/blob/6.0/docs.md
OK
https://github.com/LaravelCollective/docs/blob/6.0/docs/master/html
404

**Comment by cotiga** [comment]
Well, I summarize (my apologies for the imprecision of the previous post).
The link [docs.md] on the page:
https://github.com/LaravelCollective/docs
Leads to the page:
https://github.com/LaravelCollective/docs/blob/6.0/docs.md
This one displays 3 links which all lead to a 404
